name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello and thanks for creating your issue! I''ll get to it as soon as I can :D'
        pr-message: 'Hello and thanks for creating your PR! Make sure that you test everything to make sure it''s all good. This will help reduce my workload :D'
