name: Package Application with Pyinstaller (Linux)

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: dist/linux
